package com.tekcapsule.core.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@EqualsAndHashCode
public abstract class BaseDomainEntity<ID extends String> {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private ID id;
    @DynamoDBAttribute(attributeName = "addedBy")
    private String addedBy;
    @DynamoDBAttribute(attributeName = "updatedBy")
    private String updatedBy;
    @DynamoDBAttribute(attributeName = "addedOn")
    private String addedOn;
    @DynamoDBAttribute(attributeName = "updatedOn")
    private String updatedOn;
}
